### ISSUE TITLE
Support for fixed content areas like a footer

### ISSUE THREAD

**Issue by joho1968** [madprops/Msg#9]
Nice job!

It'd be nice if there was support out-of-the-box for fixed content areas like a footer where one could place buttons, static text, whatever. The footer should never disappear, even if content is scrolled and could have its own set of styles. Just a thought. The total "window" size obviously have to take a footer into account so that the footers don't disappear from the browser viewport.

**Comment by madprops** [comment]
Hello. That's a weird idea, why would a "window manager" provide the ability to create fixed elements like footers? That sounds like something you'd want to do with 'native' html/css layouts, unless there's some good reason I'm not seeing.

**Comment by joho1968** [comment]
Fair point :-) I'm trying to use Msg as a jquery-dialog (modal) replacement, where I'd want something like OK/CANCEL buttons at the bottom. Not necessarily both, and not necessarily always. It could be for an input form, or a file browsing dialog, or other object/item selection dialog.

I think I got this working with some CSS/HTML, but I just think it'd be nice if this could be handled natively by Msg.

**Comment by madprops** [comment]
![2020-10-08_07-27](https://user-images.githubusercontent.com/206498/95465028-e1bc5700-0937-11eb-9fdb-b34c27279a64.png)


```
<script src='msg.js'></script>

<style>
  .footer {
    height: 4rem;
    display: grid;
    grid-auto-flow: column;
    align-items: center;
    grid-gap: 0.2rem;
    background-color: #cecece;
  }

  .footer_item {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    background-color: #a7a7ba;
    height: 100%;
  }

  .Msg-content-withfooter {
    padding: 0 !important;
  }

  .content {
    font-size: 2rem;
    padding: 2rem;
  }
</style>

<script>
  window.onload = function () {
    let win = Msg.factory({
      id: 'test',
      class: 'withfooter',
      enable_titlebar: true,
      show_effect: 'none',
      close_effect: 'none',
      persistent: false
    })

    let html = `
      <div class='content'>Hello World</div>
      <div class='footer'>
        <div class='footer_item'>OK</div>
        <div class='footer_item'>Cancel</div>
      </div>
    `

    win.show(["Test", html])
  }
</script>
```

What you are trying to do can be done by simply removing 'padding' from the .Msg-content element and  then just doing your own layout inside. In this case I gave this the class called 'withfooter' and changed .Msg-content-withfooter to remove the padding (the !important is necessary). Then it's up to you to implement whatever you want inside. I think the content inside the windows should be left to the developers to implement, instead of making Msg more complex. What do you think?

**Comment by joho1968** [comment]
Thanks, yes that will work. Mine looked a bit different, but I do see your point.

````css
#Msg-content-dialog {
    background: white !important;
    padding: 2px !important;
    margin: 0 !important;
    overflow: hidden !important;
    height: calc(100% - 64px) !important;
}
.dialog-msg-body {
    background-color: rgba(255, 0, 0, 0.5) !important;
    text-align: left !important;
    padding: 0px !important;
    margin-bottom: 62px !important;
    min-width: 750px !important;
    min-height: 400px !important;
    overflow-y: scroll !important;
}
.dialog-msg-footer {
    height: 60px !important;
    background-color: rgba(0, 0, 255, 0.5) !important;
    color: white !important;
    position: absolute !important;
    bottom: 0 !important;
    left: 0 !important;
    right: 0 !important;
    padding: 2px !important;
}
````
